### ISSUE TITLE
Creating of new Sections does not work

### ISSUE THREAD

**Issue by rygos** [Hifone/Dashboard#2]
Hi,

if i create a new Section, and klick on the Save button, a message under the Button tells me, "saving in Progress" but, this never ends.
<img width="562" alt="bildschirmfoto 2016-07-18 um 19 52 18" src="https://cloud.githubusercontent.com/assets/1985803/16924773/302fdf4c-4d21-11e6-81d9-8d18ba7ff573.png">

Saving of Sections does not Work.

**Comment by lianguan** [comment]
fixed.
